# Roy

This is for me to test around and write some functions out for the class, you can create your own notebook and test around if needed. The main notebook will be `StatArb.ipynb`.

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("data/coin_universe_150K_40.csv")
df2 = pd.read_csv('data/coin_all_prices.csv')

In [17]:
df

startTime          time    0    1    2    3     4  \
0      2021-02-19T05:00:00+00:00  1.613711e+12  BTC  BNB  XRP  LTC  LINK   
1      2021-02-19T06:00:00+00:00  1.613714e+12  BTC  BNB  XRP  LTC  LINK   
2      2021-02-19T07:00:00+00:00  1.613718e+12  BTC  BNB  XRP  LTC  LINK   
3      2021-02-19T08:00:00+00:00  1.613722e+12  BTC  BNB  XRP  LTC  LINK   
4      2021-02-19T09:00:00+00:00  1.613725e+12  BTC  BNB  XRP  LTC  LINK   
...                          ...           ...  ...  ...  ...  ...   ...   
14010  2022-09-25T23:00:00+00:00  1.664147e+12  BTC  ETH  BNB  XRP   SOL   
14011  2022-09-26T00:00:00+00:00  1.664150e+12  BTC  ETH  BNB  XRP   SOL   
14012  2022-09-26T01:00:00+00:00  1.664154e+12  BTC  ETH  BNB  XRP   SOL   
14013  2022-09-26T02:00:00+00:00  1.664158e+12  BTC  ETH  BNB  XRP   SOL   
14014  2022-09-26T03:00:00+00:00  1.664161e+12  BTC  ETH  BNB  XRP   SOL   

          5     6     7  ...   30   31    32    33     34      35   36    37  \
0       BCH  DOGE   UNI  ...  ASD  SXP   SRM  TOMO   PERP  BADGER  TRU  LINA   
1       BCH  DOGE   UNI  ...  ASD  SXP   SRM  TOMO   PERP  BADGER  TRU  LINA   
2       BCH  DOGE   UNI  ...  ASD  SXP   SRM  TOMO   PERP  BADGER  TRU  LINA   
3       BCH  DOGE   UNI  ...  ASD  SXP   SRM  TOMO   PERP  BADGER  TRU  LINA   
4       BCH  DOGE   UNI  ...  ASD  SXP   SRM  TOMO   PERP  BADGER  TRU  LINA   
...     ...   ...   ...  ...  ...  ...   ...   ...    ...     ...  ...   ...   
14010  DOGE   DOT  SHIB  ...  FTM  SNX  COMP   GMT  1INCH     CRV  RSR  GALA   
14011  DOGE   DOT  SHIB  ...  FTM  SNX  COMP   GMT  1INCH     CRV  RSR  GALA   
14012  DOGE   DOT  SHIB  ...  FTM  SNX  COMP   GMT  1INCH     CRV  RSR  GALA   
14013  DOGE   DOT  SHIB  ...  FTM  SNX  COMP   GMT  1INCH     CRV  RSR  GALA   
14014  DOGE   DOT  SHIB  ...  FTM  SNX  COMP   GMT  1INCH     CRV  RSR  GALA   

         38    39  
0      MAPS  FIDA  
1      MAPS  FIDA  
2      MAPS  FIDA  
3      MAPS  FIDA  
4      MAPS  FIDA  
...     ...   ...  
14010   FXS   SRM  
14011   FXS   SRM  
14012   FXS   SRM  
14013   FXS   SRM  
14014   FXS   SRM  

[14015 rows x 42 columns]

In [18]:
from sklearn.decomposition import PCA
from Factors import Factors

In [22]:
factors = Factors(window=240, start="2021-09-26 00:00:00", finish="2022-09-25 00:00:00", coins_file='data/coin_universe_150K_40.csv', prices_file='data/coin_all_prices.csv')

In [25]:
temp = factors.symbols_df.corr() # Sigma_t

In [26]:
pca = PCA(n_components=2).fit(temp)

array([[-4.4986516 ,  0.87917237],
       [-4.50234406,  1.45482427],
       [ 1.3101435 , -2.42998338],
       [-3.11553426,  2.00447769],
       [ 6.57542093,  4.03807115],
       [ 1.51764154, -3.06328603],
       [-4.35671969,  1.44614414],
       [ 1.82772231,  0.95914808],
       [ 6.41501882,  2.95648858],
       [-3.09376109,  2.46017517],
       [ 0.65440918, -3.07487841],
       [ 6.43349517,  2.62821334],
       [-3.58574746, -0.88107926],
       [ 5.72129421, -0.07202061],
       [ 0.83676021, -3.21722774],
       [-3.60163925,  1.36061451],
       [-4.03279236,  2.46418933],
       [-4.34492644,  1.85501453],
       [-2.55409623, -1.16395592],
       [-4.39975879,  0.91751794],
       [ 3.84327248, -2.37675932],
       [-1.6835542 , -2.23407918],
       [-3.98142969,  1.2682206 ],
       [ 3.63903254, -1.71280872],
       [ 3.7087949 ,  1.23658812],
       [-3.44578642, -0.98524178],
       [ 6.93438847,  2.69776399],
       [ 0.67317891, -2.67668341],
       [-4.09999774,

## After M Code

In [1]:
from Factors import Factors

In [2]:
test = Factors(240, '2021-03-08 05:00:00', '2022-09-25 23:00:00')

In [ ]:
def get_pca(self, df):
    emp_corr = self.get_corr_mat(df)
    pca_model = PCA(n_components=2)
    pca_model.fit(emp_corr)
    # Returns the eigen vectors
    return pca_model.transform(emp_corr).components_

In [30]:
test.get_standardize_rets(test.returns_df[used_symbols].iloc[time_idx - test.M:time_idx - 1])

BTC       ETH       BNB       XRP       SOL  \
startTime                                                               
2022-09-15 23:00:00 -0.745454 -1.045223 -1.132784 -0.370914 -0.900836   
2022-09-16 00:00:00 -0.186393 -0.086114  0.693775 -0.135581  0.149597   
2022-09-16 01:00:00  0.681944  0.798607  1.803750  0.162402  0.593221   
2022-09-16 02:00:00 -0.367845 -0.755240 -0.681418 -0.711195 -0.946430   
2022-09-16 03:00:00  0.178785 -0.282408 -0.200232 -0.118116 -0.927530   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.123485 -0.552270 -0.860300 -1.107209 -1.149998   
2022-09-25 18:00:00  0.295594 -0.432877  0.767673  0.958272  0.560644   
2022-09-25 19:00:00 -0.573428  0.009367  0.056102 -0.454858 -0.667568   
2022-09-25 20:00:00 -0.108113  0.322297 -0.223197 -0.043758 -0.492818   
2022-09-25 21:00:00 -0.076496 -0.557393 -0.074542 -0.465100 -0.764084   

                         DOGE       DOT      SHIB       TRX     MATIC  ...  \
startTime                                                              ...   
2022-09-15 23:00:00 -1.107577 -0.856515 -0.743606 -0.852077 -0.906953  ...   
2022-09-16 00:00:00 -0.749044  0.380351 -0.064597  0.106098 -0.758737  ...   
2022-09-16 01:00:00  0.586554  0.774988 -0.064670  1.272056  0.887949  ...   
2022-09-16 02:00:00  0.172639 -0.766232 -0.150500 -0.775424 -0.643341  ...   
2022-09-16 03:00:00  0.328219 -0.411856 -0.494406 -0.379080 -0.872652  ...   
...                       ...       ...       ...       ...       ...  ...   
2022-09-25 17:00:00 -0.564967 -0.817866 -0.513157 -0.963312 -0.700249  ...   
2022-09-25 18:00:00  0.294996  0.295927 -0.247502  0.695545  0.164918  ...   
2022-09-25 19:00:00 -0.012684 -0.023909  0.021013  0.406416  0.197603  ...   
2022-09-25 20:00:00 -0.696499  0.015987 -0.068732 -0.488402 -0.155015  ...   
2022-09-25 21:00:00 -0.644462 -0.523490 -0.607765 -0.456234 -0.648025  ...   

                          FTM       SNX      COMP       GMT     1INCH  \
startTime                                                               
2022-09-15 23:00:00 -0.939353 -0.904613  0.318666 -1.434068 -1.081932   
2022-09-16 00:00:00 -0.216989 -0.290768 -0.651835  0.725708 -0.312398   
2022-09-16 01:00:00  1.346946  0.293917 -0.106528  0.619588  0.869267   
2022-09-16 02:00:00 -0.389558 -0.680560 -1.180383 -0.380485 -0.575818   
2022-09-16 03:00:00 -0.566403 -0.195322 -1.798124 -0.653383  0.087041   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.713060 -0.575888  0.399346 -0.542698 -0.354503   
2022-09-25 18:00:00  0.599207  0.809431  0.483845  0.060698  0.083386   
2022-09-25 19:00:00 -0.072185 -0.235636 -0.247478  0.024501 -0.665964   
2022-09-25 20:00:00 -0.313253 -0.066255 -0.074866 -0.038839 -1.000705   
2022-09-25 21:00:00 -0.502216 -0.726345 -0.520410 -1.007682 -0.916792   

                          CRV       RSR      GALA       FXS       SRM  
startTime                                                              
2022-09-15 23:00:00 -0.798820 -0.551153 -0.636559 -0.613420 -0.871927  
2022-09-16 00:00:00 -0.254639 -0.154443  0.182585  0.504504 -0.575954  
2022-09-16 01:00:00  1.761491  0.131376  0.770129  0.782896  0.638255  
2022-09-16 02:00:00 -1.710576 -0.325220 -0.811007 -1.445775 -0.727347  
2022-09-16 03:00:00 -0.806889 -0.097319 -0.052795 -0.001005 -0.122735  
...                       ...       ...       ...       ...       ...  
2022-09-25 17:00:00 -0.332118  0.220228 -0.740106 -0.309609 -0.448022  
2022-09-25 18:00:00 -0.466707 -0.413338  0.673115 -0.170157 -0.130231  
2022-09-25 19:00:00 -0.192608 -0.176705 -0.002282  0.323582  0.189678  
2022-09-25 20:00:00 -0.297566 -0.852405 -0.405815  0.534725 -0.290079  
2022-09-25 21:00:00 -0.428578 -1.263220 -0.542892  0.252214 -0.290932  

[239 rows x 40 columns]

In [31]:
test.asset_std

array([0.00666259, 0.00936335, 0.005592  , 0.01748996, 0.00851712,
       0.00826365, 0.00802722, 0.00996661, 0.00377695, 0.00866628,
       0.00871082, 0.00923512, 0.0144445 , 0.01003696, 0.00881077,
       0.00657196, 0.01048349, 0.00921054, 0.01359878, 0.00810655,
       0.01572681, 0.0150628 , 0.00894067, 0.00716507, 0.00997348,
       0.00910969, 0.01211732, 0.00949106, 0.0085436 , 0.01855533,
       0.00823744, 0.00991372, 0.01281575, 0.00881877, 0.00886721,
       0.01114445, 0.01522244, 0.00901769, 0.00828473, 0.00831906])

In [20]:
emp_corr = test.get_corr_mat(st_rets)
pca_model = PCA(n_components=2)
pca_model.fit(emp_corr)

<IPython.core.display.Javascript object>

PCA(n_components=2)

In [40]:
st_rets

BTC       ETH       BNB       XRP       SOL  \
startTime                                                               
2022-09-15 23:00:00 -0.745454 -1.045223 -1.132784 -0.370914 -0.900836   
2022-09-16 00:00:00 -0.186393 -0.086114  0.693775 -0.135581  0.149597   
2022-09-16 01:00:00  0.681944  0.798607  1.803750  0.162402  0.593221   
2022-09-16 02:00:00 -0.367845 -0.755240 -0.681418 -0.711195 -0.946430   
2022-09-16 03:00:00  0.178785 -0.282408 -0.200232 -0.118116 -0.927530   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.123485 -0.552270 -0.860300 -1.107209 -1.149998   
2022-09-25 18:00:00  0.295594 -0.432877  0.767673  0.958272  0.560644   
2022-09-25 19:00:00 -0.573428  0.009367  0.056102 -0.454858 -0.667568   
2022-09-25 20:00:00 -0.108113  0.322297 -0.223197 -0.043758 -0.492818   
2022-09-25 21:00:00 -0.076496 -0.557393 -0.074542 -0.465100 -0.764084   

                         DOGE       DOT      SHIB       TRX     MATIC  ...  \
startTime                                                              ...   
2022-09-15 23:00:00 -1.107577 -0.856515 -0.743606 -0.852077 -0.906953  ...   
2022-09-16 00:00:00 -0.749044  0.380351 -0.064597  0.106098 -0.758737  ...   
2022-09-16 01:00:00  0.586554  0.774988 -0.064670  1.272056  0.887949  ...   
2022-09-16 02:00:00  0.172639 -0.766232 -0.150500 -0.775424 -0.643341  ...   
2022-09-16 03:00:00  0.328219 -0.411856 -0.494406 -0.379080 -0.872652  ...   
...                       ...       ...       ...       ...       ...  ...   
2022-09-25 17:00:00 -0.564967 -0.817866 -0.513157 -0.963312 -0.700249  ...   
2022-09-25 18:00:00  0.294996  0.295927 -0.247502  0.695545  0.164918  ...   
2022-09-25 19:00:00 -0.012684 -0.023909  0.021013  0.406416  0.197603  ...   
2022-09-25 20:00:00 -0.696499  0.015987 -0.068732 -0.488402 -0.155015  ...   
2022-09-25 21:00:00 -0.644462 -0.523490 -0.607765 -0.456234 -0.648025  ...   

                          FTM       SNX      COMP       GMT     1INCH  \
startTime                                                               
2022-09-15 23:00:00 -0.939353 -0.904613  0.318666 -1.434068 -1.081932   
2022-09-16 00:00:00 -0.216989 -0.290768 -0.651835  0.725708 -0.312398   
2022-09-16 01:00:00  1.346946  0.293917 -0.106528  0.619588  0.869267   
2022-09-16 02:00:00 -0.389558 -0.680560 -1.180383 -0.380485 -0.575818   
2022-09-16 03:00:00 -0.566403 -0.195322 -1.798124 -0.653383  0.087041   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.713060 -0.575888  0.399346 -0.542698 -0.354503   
2022-09-25 18:00:00  0.599207  0.809431  0.483845  0.060698  0.083386   
2022-09-25 19:00:00 -0.072185 -0.235636 -0.247478  0.024501 -0.665964   
2022-09-25 20:00:00 -0.313253 -0.066255 -0.074866 -0.038839 -1.000705   
2022-09-25 21:00:00 -0.502216 -0.726345 -0.520410 -1.007682 -0.916792   

                          CRV       RSR      GALA       FXS       SRM  
startTime                                                              
2022-09-15 23:00:00 -0.798820 -0.551153 -0.636559 -0.613420 -0.871927  
2022-09-16 00:00:00 -0.254639 -0.154443  0.182585  0.504504 -0.575954  
2022-09-16 01:00:00  1.761491  0.131376  0.770129  0.782896  0.638255  
2022-09-16 02:00:00 -1.710576 -0.325220 -0.811007 -1.445775 -0.727347  
2022-09-16 03:00:00 -0.806889 -0.097319 -0.052795 -0.001005 -0.122735  
...                       ...       ...       ...       ...       ...  
2022-09-25 17:00:00 -0.332118  0.220228 -0.740106 -0.309609 -0.448022  
2022-09-25 18:00:00 -0.466707 -0.413338  0.673115 -0.170157 -0.130231  
2022-09-25 19:00:00 -0.192608 -0.176705 -0.002282  0.323582  0.189678  
2022-09-25 20:00:00 -0.297566 -0.852405 -0.405815  0.534725 -0.290079  
2022-09-25 21:00:00 -0.428578 -1.263220 -0.542892  0.252214 -0.290932  

[239 rows x 40 columns]

In [39]:
st_rets['BTC'].std()

1.0020986381949977

In [32]:
pca_model.components_ / test.asset_std

array([[-27.85419315, -20.95219027, -32.25858143,  -4.70890472,
        -21.4816824 , -19.5448842 , -23.28722867, -15.47575006,
        -45.20864026, -22.15601897, -20.97409366, -19.74310537,
         -6.31533069, -16.490234  , -19.7731025 , -29.74060168,
        -12.17125882, -21.29243929,  -4.30958035, -21.35110044,
         -5.56057571,  -3.10394272, -19.95334466, -26.10150353,
        -16.34775111, -21.23325923, -13.26066052, -18.89779384,
        -18.97623254,  -2.72218956, -22.82359218, -14.96960988,
         -4.69512104, -19.92320657, -18.62506798, -16.00461861,
         -3.24059315, -19.80049181,  -1.92627355, -21.30867101],
       [ 31.77066557,  20.64582249,  -3.09830002,  -8.81557578,
         -3.56529949,  11.46160657,   4.14428363,  19.88346735,
         -0.29476523,   0.5444701 ,   0.27058979,  -9.00947828,
         -7.62663751,  -3.08176367,   9.80927701,  23.71262273,
        -11.54779734,  -1.56828824, -30.33711486, -10.00822127,
          7.26294895, -25.59395965,  -4

In [3]:
eigen_vectors = test.test_pca("2022-09-25 23:00:00")
eigen_vectors

array([[-4.38226794, -0.27856072],
       [-4.50089408, -0.27255015],
       [-4.47829111, -0.03627233],
       [-3.23075863,  0.18159113],
       [-4.63087559, -0.02151469],
       [-4.01942494, -0.17751929],
       [-4.83969458, -0.06310755],
       [-4.00610779, -0.24743194],
       [-4.53215179, -0.02122083],
       [-4.92684557, -0.03744129],
       [-4.74990015, -0.02776144],
       [-4.71277838,  0.05762732],
       [-3.55482598,  0.21672121],
       [-4.47303666,  0.01159203],
       [-4.52029697, -0.11549462],
       [-4.77239376, -0.20988204],
       [-3.94593933,  0.12520285],
       [-4.80236711, -0.039917  ],
       [-3.08494859,  0.47168597],
       [-4.52869783,  0.05097366],
       [-3.21990202, -0.06071603],
       [-2.85603099,  0.50465602],
       [-4.58416653,  0.01200904],
       [-4.91164374,  0.04544098],
       [-4.46314358,  0.05082461],
       [-4.89923042, -0.06499481],
       [-4.18326707, -0.06868369],
       [-4.64331486,  0.00859025],
       [-4.58949455,

In [5]:
time = '2022-09-25 23:00:00'

In [6]:
used_symbols = list(test.symbols_df.loc[time])
time_idx = test.returns_df.index.get_loc(time)

In [55]:
st_rets = test.get_standardize_rets(test.returns_df[used_symbols].iloc[time_idx - test.M:time_idx - 1])

In [56]:
temp_df = test.returns_df[used_symbols].iloc[time_idx - test.M:time_idx - 1]

In [62]:
sc = StandardScaler()

In [65]:
temp_df_scaled = pd.DataFrame(sc.fit_transform(temp_df), index=temp_df.index, columns=temp_df.columns)

In [69]:
emp_corr = test.get_corr_mat(temp_df_scaled)
pca_model = PCA(n_components=2)
pca_model.fit(emp_corr)

<IPython.core.display.Javascript object>

PCA(n_components=2)

In [70]:
eigenvalues = pca_model.explained_variance_
eigenvectors = pca_model.components_

In [79]:
eigenvalues

array([0.54182506, 0.03037894])

In [82]:
eigenvectors[1].sum()

-0.5361674398493241

In [86]:
eigenvectors / temp_df.std()

ValueError: Length of values (2) does not match length of index (40)

In [90]:
eigenvectors = pd.DataFrame(eigenvectors, columns=temp_df.columns)

In [102]:
((eigenvectors / temp_df.std()))@temp_df.T


startTime  2022-09-15 23:00:00  2022-09-16 00:00:00  2022-09-16 01:00:00  \
0                     6.045791             0.710135            -4.654944   
1                     0.026929             0.066541            -0.526460   

startTime  2022-09-16 02:00:00  2022-09-16 03:00:00  2022-09-16 04:00:00  \
0                     3.837639             1.973192            -3.462252   
1                    -0.035694             0.331731            -1.692765   

startTime  2022-09-16 05:00:00  2022-09-16 06:00:00  2022-09-16 07:00:00  \
0                    -0.669136             0.139587             0.235006   
1                     1.021190             0.417089            -0.347982   

startTime  2022-09-16 08:00:00  ...  2022-09-25 12:00:00  2022-09-25 13:00:00  \
0                     1.521285  ...            -2.144496             2.011615   
1                    -0.146431  ...             0.419210            -0.325071   

startTime  2022-09-25 14:00:00  2022-09-25 15:00:00  2022-09-25 16:00:00  \
0                     7.174851             1.768176            -3.286774   
1                    -1.392444             0.288766            -0.559815   

startTime  2022-09-25 17:00:00  2022-09-25 18:00:00  2022-09-25 19:00:00  \
0                     3.912022            -1.793457             0.583561   
1                    -0.463297            -1.272054             0.559141   

startTime  2022-09-25 20:00:00  2022-09-25 21:00:00  
0                     1.621499             3.177612  
1                     0.917306             0.988291  

[2 rows x 239 columns]

In [94]:
temp_df

BTC       ETH       BNB       XRP       SOL  \
startTime                                                               
2022-09-15 23:00:00 -0.005144 -0.010337 -0.006270 -0.004576 -0.007736   
2022-09-16 00:00:00 -0.001419 -0.001356  0.003944 -0.000460  0.001211   
2022-09-16 01:00:00  0.004366  0.006927  0.010151  0.004752  0.004989   
2022-09-16 02:00:00 -0.002628 -0.007622 -0.003746 -0.010527 -0.008124   
2022-09-16 03:00:00  0.001014 -0.003194 -0.001056 -0.000154 -0.007963   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.001000 -0.005721 -0.004747 -0.017453 -0.009858   
2022-09-25 18:00:00  0.001792 -0.004603  0.004357  0.018672  0.004712   
2022-09-25 19:00:00 -0.003998 -0.000462  0.000378 -0.006044 -0.005749   
2022-09-25 20:00:00 -0.000898  0.002468 -0.001184  0.001146 -0.004260   
2022-09-25 21:00:00 -0.000687 -0.005769 -0.000353 -0.006223 -0.006571   

                         DOGE       DOT      SHIB       TRX     MATIC  ...  \
startTime                                                              ...   
2022-09-15 23:00:00 -0.008983 -0.007324 -0.007621 -0.003333 -0.008316  ...   
2022-09-16 00:00:00 -0.006021  0.002604 -0.000853  0.000286 -0.007031  ...   
2022-09-16 01:00:00  0.005016  0.005772 -0.000854  0.004689  0.007240  ...   
2022-09-16 02:00:00  0.001596 -0.006600 -0.001709 -0.003044 -0.006031  ...   
2022-09-16 03:00:00  0.002882 -0.003755 -0.005137 -0.001547 -0.008018  ...   
...                       ...       ...       ...       ...       ...  ...   
2022-09-25 17:00:00 -0.004499 -0.007014 -0.005324 -0.003754 -0.006524  ...   
2022-09-25 18:00:00  0.002607  0.001926 -0.002676  0.002512  0.000974  ...   
2022-09-25 19:00:00  0.000064 -0.000641  0.000000  0.001420  0.001257  ...   
2022-09-25 20:00:00 -0.005586 -0.000321 -0.000894 -0.001960 -0.001799  ...   
2022-09-25 21:00:00 -0.005156 -0.004651 -0.006267 -0.001838 -0.006072  ...   

                          FTM       SNX      COMP       GMT     1INCH  \
startTime                                                               
2022-09-15 23:00:00 -0.008025 -0.009365  0.004568 -0.012943 -0.009522   
2022-09-16 00:00:00 -0.002074 -0.003280 -0.007870  0.006104 -0.002699   
2022-09-16 01:00:00  0.010809  0.002516 -0.000881  0.005168  0.007779   
2022-09-16 02:00:00 -0.003496 -0.007144 -0.014644 -0.003651 -0.005034   
2022-09-16 03:00:00 -0.004953 -0.002334 -0.022560 -0.006058  0.000843   
...                       ...       ...       ...       ...       ...   
2022-09-25 17:00:00 -0.006161 -0.006107  0.005602 -0.005082 -0.003072   
2022-09-25 18:00:00  0.004649  0.007627  0.006685  0.000239  0.000811   
2022-09-25 19:00:00 -0.000881 -0.002733 -0.002688 -0.000080 -0.005834   
2022-09-25 20:00:00 -0.002867 -0.001054 -0.000476 -0.000638 -0.008802   
2022-09-25 21:00:00 -0.004424 -0.007598 -0.006186 -0.009182 -0.008058   

                          CRV       RSR      GALA       FXS       SRM  
startTime                                                              
2022-09-15 23:00:00 -0.009569 -0.006908 -0.006326 -0.006007 -0.007500  
2022-09-16 00:00:00 -0.003505 -0.000870  0.001061  0.003254 -0.005038  
2022-09-16 01:00:00  0.018964  0.003481  0.006359  0.005561  0.005063  
2022-09-16 02:00:00 -0.019730 -0.003469 -0.007899 -0.012903 -0.006297  
2022-09-16 03:00:00 -0.009659  0.000000 -0.001062 -0.000934 -0.001267  
...                       ...       ...       ...       ...       ...  
2022-09-25 17:00:00 -0.004368  0.004834 -0.007260 -0.003490 -0.003974  
2022-09-25 18:00:00 -0.005868 -0.004811  0.005484 -0.002335 -0.001330  
2022-09-25 19:00:00 -0.002813 -0.001208 -0.000606  0.001755  0.001332  
2022-09-25 20:00:00 -0.003983 -0.011494 -0.004245  0.003505 -0.002660  
2022-09-25 21:00:00 -0.005443 -0.017748 -0.005481  0.001164 -0.002667  

[239 rows x 40 columns]

In [78]:
(eigenvectors[0] / temp_df.std())

BTC     -27.795860
ETH     -20.908311
BNB     -32.191024
XRP      -4.699043
SOL     -21.436695
DOGE    -19.503952
DOT     -23.238460
SHIB    -15.443340
TRX     -45.113962
MATIC   -22.109619
AVAX    -20.930169
UNI     -19.701759
ATOM     -6.302105
LINK    -16.455699
LTC     -19.731693
FTT     -29.678318
CRO     -12.145769
NEAR    -21.247848
ALGO     -4.300555
BCH     -21.306386
APE      -5.548931
CHZ      -3.097442
SAND    -19.911558
MANA    -26.046841
AXS     -16.313515
AAVE    -21.188792
LDO     -13.232889
GRT     -18.858217
MKR     -18.936492
CEL      -2.716489
FTM     -22.775794
SNX     -14.938260
COMP     -4.685288
GMT     -19.881483
1INCH   -18.586063
CRV     -15.971101
RSR      -3.233807
GALA    -19.759025
FXS      -1.922239
SRM     -21.264045
dtype: float64

In [67]:
temp_df_scaled.std()

BTC      1.002099
ETH      1.002099
BNB      1.002099
XRP      1.002099
SOL      1.002099
DOGE     1.002099
DOT      1.002099
SHIB     1.002099
TRX      1.002099
MATIC    1.002099
AVAX     1.002099
UNI      1.002099
ATOM     1.002099
LINK     1.002099
LTC      1.002099
FTT      1.002099
CRO      1.002099
NEAR     1.002099
ALGO     1.002099
BCH      1.002099
APE      1.002099
CHZ      1.002099
SAND     1.002099
MANA     1.002099
AXS      1.002099
AAVE     1.002099
LDO      1.002099
GRT      1.002099
MKR      1.002099
CEL      1.002099
FTM      1.002099
SNX      1.002099
COMP     1.002099
GMT      1.002099
1INCH    1.002099
CRV      1.002099
RSR      1.002099
GALA     1.002099
FXS      1.002099
SRM      1.002099
dtype: float64

In [66]:
temp_df.std()

BTC      0.006677
ETH      0.009383
BNB      0.005604
XRP      0.017527
SOL      0.008535
DOGE     0.008281
DOT      0.008044
SHIB     0.009988
TRX      0.003785
MATIC    0.008684
AVAX     0.008729
UNI      0.009254
ATOM     0.014475
LINK     0.010058
LTC      0.008829
FTT      0.006586
CRO      0.010505
NEAR     0.009230
ALGO     0.013627
BCH      0.008124
APE      0.015760
CHZ      0.015094
SAND     0.008959
MANA     0.007180
AXS      0.009994
AAVE     0.009129
LDO      0.012143
GRT      0.009511
MKR      0.008562
CEL      0.018594
FTM      0.008255
SNX      0.009935
COMP     0.012843
GMT      0.008837
1INCH    0.008886
CRV      0.011168
RSR      0.015254
GALA     0.009037
FXS      0.008302
SRM      0.008337
dtype: float64

In [52]:
temp_df = test.get_standardize_rets(temp_df)

In [54]:
temp_df.std()

BTC      1.002099
ETH      1.002099
BNB      1.002099
XRP      1.002099
SOL      1.002099
DOGE     1.002099
DOT      1.002099
SHIB     1.002099
TRX      1.002099
MATIC    1.002099
AVAX     1.002099
UNI      1.002099
ATOM     1.002099
LINK     1.002099
LTC      1.002099
FTT      1.002099
CRO      1.002099
NEAR     1.002099
ALGO     1.002099
BCH      1.002099
APE      1.002099
CHZ      1.002099
SAND     1.002099
MANA     1.002099
AXS      1.002099
AAVE     1.002099
LDO      1.002099
GRT      1.002099
MKR      1.002099
CEL      1.002099
FTM      1.002099
SNX      1.002099
COMP     1.002099
GMT      1.002099
1INCH    1.002099
CRV      1.002099
RSR      1.002099
GALA     1.002099
FXS      1.002099
SRM      1.002099
dtype: float64

In [16]:
eigen_vectors.T / test.asset_std

array([[-6.57742322e+02, -4.80692825e+02, -8.00838339e+02,
        -1.84720765e+02, -5.43714052e+02, -4.86397981e+02,
        -6.02910323e+02, -4.01952747e+02, -1.19994915e+03,
        -5.68507376e+02, -5.45287502e+02, -5.10310660e+02,
        -2.46102374e+02, -4.45656492e+02, -5.13042108e+02,
        -7.26175192e+02, -3.76395436e+02, -5.21399195e+02,
        -2.26854782e+02, -5.58646530e+02, -2.04739713e+02,
        -1.89608257e+02, -5.12731752e+02, -6.85498008e+02,
        -4.47500970e+02, -5.37804119e+02, -3.45230465e+02,
        -4.89230522e+02, -5.37185326e+02, -1.41481370e+02,
        -5.97163508e+02, -4.52455293e+02, -2.34164105e+02,
        -5.10883042e+02, -5.13883745e+02, -4.20738097e+02,
        -1.94403998e+02, -5.23004324e+02, -2.80580974e+02,
        -5.61193657e+02],
       [-4.18096694e+01, -2.91081951e+01, -6.48646393e+00,
         1.03825931e+01, -2.52605304e+00, -2.14819352e+01,
        -7.86169261e+00, -2.48260791e+01, -5.61850414e+00,
        -4.32033994e+00, -3.18

In [4]:
test.asset_std

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])